Bookshop/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookshop.Models
{
    public class ApplicationDbContext:DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options):base(options)
        {
                
        }

        public DbSet<Book> Books { get; set; }

    }
}

Bookshop/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Bookshop.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public string Author { get; set; }
        [Range(0.01,100.00,ErrorMessage ="Price must be between $0.01 and $100.00")]
        [DataType(DataType.Currency)]
        public double Price { get; set; }
    }
}

Bookshop/Models/ErrorViewModel.cs
using System;

namespace Bookshop.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bookshop/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookshop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bookshop.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BooksController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Books.ToList());
        }

        //GET Book/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        //GET EDIT BOOK
        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var book = await _context.Books.SingleOrDefaultAsync(m => m.Id == id);

             if(book == null)
            {
                return NotFound();
            }
            return View(book);
        }
        //EDIT POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Update(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }
        //GET DELETE BOOK
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = await _context.Books.SingleOrDefaultAsync(m => m.Id == id);

            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }
        //EDIT DELETE
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveBook(int? id)
        {
           
                var book = await _context.Books.SingleOrDefaultAsync(m => m.Id == id);
                _context.Books.Remove(book);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
           
          //  return View(book);
        }
    }
}

Bookshop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Bookshop.Models;

namespace Bookshop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bookshop/Views/Books/Create.cshtml
@model Bookshop.Models.Book
@{
    ViewData["Title"] = "Create";
}

<br/>
<h2>Add New Book</h2>
<hr/>

<form asp-action="Create">
    <div class="container">
        <div asp-validation-summary="ModelOnly" class="text-danger"/>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Author"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Author" class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Price" class="form-control" />
                </div>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-sm btn-primary" />
            <a asp-action="Index" class="btn btn-sm btn-success">Back to List</a>
        </div>
    </div>
</form>

Bookshop/Views/Books/Delete.cshtml
@model Bookshop.Models.Book
@{
    ViewData["Title"] = "Delete";
}

<br />
<h2>Delete Book</h2>
<hr />

<form asp-action="Delete">
    <div class="container">
        <input asp-for="Id" hidden/>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" disabled class="form-control" />
                </div>
               
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Author"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Author" disabled class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Price" disabled class="form-control" />
                </div>
           
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-sm btn-danger" />
            <a asp-action="Index" class="btn btn-sm btn-success">Back to List</a>
        </div>
    </div>
</form>

Bookshop/Views/Books/Edit.cshtml
@model Bookshop.Models.Book
@{
    ViewData["Title"] = "Edit";
}

<br />
<h2>Edit New Book</h2>
<hr />

<form asp-action="Edit">
    <div class="container">
        <div asp-validation-summary="ModelOnly" class="text-danger" />
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Author"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Author" class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Price" class="form-control" />
                </div>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Update" class="btn btn-sm btn-primary" />
            <a asp-action="Index" class="btn btn-sm btn-success">Back to List</a>
        </div>
    </div>
</form>

Bookshop/Views/Books/Index.cshtml
@model IEnumerable<Bookshop.Models.Book>
@{
    ViewData["Title"] = "Index";
}

<br />
<h1>Book List</h1>
<hr/>
<p>
    <a asp-action="Create" class="btn btn-sm btn-primary">Create New</a>
</p>

@if (Model.Count() > 0)
{
    //Display all books.
    <div class="border">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Author)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Price)
                </th>
                <th>

                </th>
            </tr>
            @foreach(var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(m => item.Name)
            </td>
            <td>
                @Html.DisplayFor(m => item.Author)
            </td>
            <td>
                @Html.DisplayFor(m => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-success">Edit</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Details</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>

            </td>
        </tr>
            }
        </table>

    </div>
}
else
{
    <div>No Books Exists... Please Add a new book.</div>
}

Bookshop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    Book List MVC Application   
</div>

Bookshop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookshop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Book List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Bookshop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>